### PR TITLE
updates in readme file

### PR DESCRIPTION
**Pull request by bhavya1006**
I have some edits for the title and in python section introduction and sources are added.
review: @yashdev9274

### CODE REVIEW

**Review by yashdev9274 — COMMENTED** [review]
leave it for review

**Review by Sandeep-RN — CHANGES_REQUESTED** [review]
Under the "Some Reading Resource" section,
I think we should have some space between the images, 
because sometimes all the images are redirected to the same website, it happened to me while testing it, someone else please check it and confirm it.

**Review by yashdev9274 — APPROVED** [review]
/lgtm

**Review by yashdev9274 — APPROVED** [review]
/lgtm

**Review by yashdev9274 — APPROVED** [review]
/approved

**Comment by yashdev9274** [comment]
@bhavya1006  next time try to keep your commits less , I mean don't include to much (commit) in just 1 PR try to divide it into 2 or more , it can help us to review the PR easily and it won't take us too much time

**Comment by bhavya1006** [comment]
@yashdev9274 I will make sure about that, thanks for the review for image spacing @Sandeep-RN ( I will make sure that also )

**Pull request merged**
